### ISSUE TITLE
dates object does not have .get_text()

### ISSUE THREAD

**Issue by khanrahan** [mdlavin/lendingclub-statement-converter#1]
Hey there,

I get the below error when trying to run the parse.  I'm trying to sort this out but wanted to post this as well.

Using python 2.7.8.

Thanks!

```
python parse.py /Users/K/Downloads/Monthly_Statement_2015_04.pdf 
Split Loan Interest was not found, so it will be ignored
!Type:Bank
Traceback (most recent call last):
  File "parse.py", line 206, in <module>
    date = findStatementDate(findPageWithSection(pdf, "CASH DETAILS"))
  File "parse.py", line 171, in findStatementDate
    dateMatch = dateRegex.match(dates.get_text().strip())
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by mdlavin** [comment]
I just pushed one local commit that hadn't been pushed yet, maybe it will help.  Another possibility is that the statement structure changed in the last couple of months.  I haven't checked my statements since the end of last year (I know it's bad)
